[phases.setup]
nixPkgs = ["jdk17", "maven", "imagemagick"]

[phases.install]
cmds = ["./mvnw dependency:go-offline -B"]

[phases.build]
cmds = ["./mvnw clean package -DskipTests"]

[start]
cmd = "java -jar target/change-my-image-0.0.1-SNAPSHOT.jar"









